name: GitHub App installation access token generator
description: Generate an installation access token for a GitHub App that can be for instance used to clone other repositories
inputs:
  private-key:
    description: Private key for the GitHub App
    required: true
  app-id:
    description: GitHub App ID
    required: true
  repo:
    description: Override GITHUB_REPOSITORY when creating the installation ID
    required: false
outputs:
  token:
    description: Installation access token for the GitHub App
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' 
    - name: Generete token
      shell: bash
      env: 
        PRIVATE_KEY: ${{ inputs.private-key }}
        APP_ID: ${{ inputs.app-id }}
      run:  bash -x ${{ github.action_path }}/get-installation-access-token.sh
author: Christer Edvartsen <christer.edvartsen@nav.no>
branding:
  icon: unlock
  color: red
