name: GitHub App installation token generator
description: Generate an installation token for a GitHub App that can be for instance used to clone other repositories
inputs:
  private-key:
    description: Private key for the GitHub App
    required: true
  app-id:
    description: GitHub App ID
    required: true
outputs:
  token:
    description: Installation token for the GitHub App
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.private-key }}
    - ${{ inputs.app-id }}